---
- name: My First Configuration Playbook
  hosts: local_servers
  become: yes

  tasks:
    - name: Ensure git is Installed
      ansible.builtin.yum:
        name: git
        state: present

    - name: Create a Welcome Message File for our Project
      ansible.builtin.copy:
        dest: /tmp/devops_welcome.txt
        content: "/n Hello! this server is configured using ansible /n"
